name = "Table3Landais"
uuid = "686470d1-6c34-4cba-9bb9-9529f840be98"
authors = ["Elvin Le Pouhaër <elvin.lepouhaer@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
